// crypto-ts: cryptography primitives and wrappers
// Copyright 2026 Dark Bio AG. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//! HKDF cryptography wrappers and parametrization.
//!
//! https://datatracker.ietf.org/doc/html/rfc5869

use wasm_bindgen::prelude::*;
use zeroize::Zeroizing;

/// Maximum output length for SHA-256 HKDF (255 * 32 bytes per RFC 5869). The
/// underlying implementation panics beyond it, which inside WASM would trap
/// and poison the instance, so it is checked up front.
const MAX_OUTPUT_LEN: usize = 255 * 32;

/// Derives a key from the secret, salt, and info using HKDF-SHA256, returning a
/// byte array that can be used as a cryptographic key.
///
/// The out_len may not exceed the maximum output length for SHA-256 HKDF, which
/// is 255 * 32 = 8160 bytes. The secret and the key are wiped from WASM memory
/// before return.
#[wasm_bindgen]
pub fn hkdf_key(
    secret: Vec<u8>,
    salt: &[u8],
    info: &[u8],
    out_len: usize,
) -> Result<js_sys::Uint8Array, JsError> {
    let secret = Zeroizing::new(secret);
    if out_len > MAX_OUTPUT_LEN {
        return Err(JsError::new("output length must be at most 8160 bytes"));
    }
    let key = darkbio_crypto::hkdf::key_with_len(&secret, salt, info, out_len);
    Ok(js_sys::Uint8Array::from(&key[..]))
}

/// Generates a pseudorandom key for use with hkdf_expand from an input secret
/// and an optional independent salt.
///
/// Only use this function if you need to reuse the extracted key with multiple
/// expand invocations and different context values. Most common scenarios,
/// including the generation of multiple keys, should use hkdf_key instead.
/// The secret and the key are wiped from WASM memory before return.
#[wasm_bindgen]
pub fn hkdf_extract(secret: Vec<u8>, salt: &[u8]) -> js_sys::Uint8Array {
    let secret = Zeroizing::new(secret);
    let prk = darkbio_crypto::hkdf::extract(&secret, salt);
    js_sys::Uint8Array::from(&prk[..])
}

/// Derives a key using the given pseudorandom key and optional context info,
/// skipping the extraction step.
///
/// The pseudorandom key should have been generated by hkdf_extract, or be a
/// uniformly random or pseudorandom cryptographically strong key. See RFC 5869,
/// Section 3.3. Most common scenarios will want to use hkdf_key instead. The
/// pseudorandom key and the derived key are wiped from WASM memory before
/// return.
#[wasm_bindgen]
pub fn hkdf_expand(
    prk: Vec<u8>,
    info: &[u8],
    out_len: usize,
) -> Result<js_sys::Uint8Array, JsError> {
    let prk = Zeroizing::new(prk);
    if out_len > MAX_OUTPUT_LEN {
        return Err(JsError::new("output length must be at most 8160 bytes"));
    }
    let prk: Zeroizing<[u8; 32]> = Zeroizing::new(
        prk.as_slice()
            .try_into()
            .map_err(|_| JsError::new("prk must be 32 bytes"))?,
    );
    let key = darkbio_crypto::hkdf::expand_with_len(&prk, info, out_len);
    Ok(js_sys::Uint8Array::from(&key[..]))
}
